### ISSUE TITLE
API token is not enough to authenticate as stated in the doc

### ISSUE THREAD

**Issue by fmarchalemisys** [paynl/sdk-alliance#9]
At step 2 "Your APItoken", the doc states that one must provide the API token:

    \Paynl\Config::setApiToken('YOUR_API_TOKEN');

The API token code must be provided too (at least to get the merchant list) with

    \Paynl\Config::setTokenCode('AT-....-....');

That piece of information is missing from the doc.

**Comment by andypieters** [comment]
Updated
